ignores:
  [
    '@babel/*',
    '@types/*',
    'sort-package-json',
    'ts-node',
    'autoprefixer',
    'postcss-import',
    'depcheck',
    'jest-environment-jsdom',
    'semantic-release',
  ]
