# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn
        working-directory: storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: storybook
          token: ${{ secrets.GH_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
